# Generated by Django 4.1 on 2022-09-03 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='special_user',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
