# Generated by Django 4.1 on 2022-09-05 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_special', models.BooleanField(default=False, verbose_name='special article?')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.SlugField()),
                ('description', models.TextField(verbose_name='description')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnail/', verbose_name='thumbnail')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date:')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created:')),
                ('updated', models.DateField(auto_now=True, verbose_name='updated article:')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('I', 'Investigation'), ('B', 'Back')], max_length=1, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.article', verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='category title')),
                ('status', models.BooleanField(default=True, verbose_name='category status')),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='main category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles_category', to='blog.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
