# Generated by Django 4.1 on 2022-09-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ipaddress_alter_comment_comment_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
