# Generated by Django 4.1 on 2022-09-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_created_alter_article_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('I', 'Investigaation'), ('B', 'Back')], max_length=1, verbose_name='status'),
        ),
    ]
